# idea from https://github.com/analogdevicesinc/libsmu/blob/master/appveyor.yml
os: Visual Studio 2015
clone_depth: 1

configuration:
  - Release
#  - Debug

install:
  - git clone https://github.com/skandhurkat/Getopt-for-Visual-Studio "C:\projects\Getopt-for-Visual-Studio"
  - git clone https://github.com/libusb/libusb.git "C:\projects\libusb"

build_script:
  - ps: pushd "C:\projects\libusb"
  - msbuild msvc\libusb_2015.sln /p:Platform=Win32 /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild msvc\libusb_2015.sln /p:Platform=x64 /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: popd
  - dir
  - set PATH=%PATH%;C:\MinGW\bin
  - msbuild uhubctl.vcxproj /p:Platform=Win32 /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild uhubctl.vcxproj /p:Platform=x64 /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - dir
  - dir Win32\*
  - dir x64\*

# https://www.appveyor.com/docs/packaging-artifacts/
artifacts:
  - path: Win32/Release/uhubctl.exe
    name: uhubctl-win32
    type: zip

  - path: x64/Release/uhubctl.exe
    name: uhubctl-x64
    type: zip

# https://www.appveyor.com/docs/deployment/github/
# deploy:
  # release: uhubctl-v$(appveyor_build_version)
  # description: 'uhubctl: new version'
  # provider: GitHub
  # auth_token:
  #  secure: <your encrypted token> # your encrypted token from GitHub
  # artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  # draft: false
  # prerelease: false
  # on:
  #  branch: master                 # release from master branch only
  # appveyor_repo_tag: true        # deploy on tag push only
